github:
  release: true
  assets: ["bin/should-i-watch-this.*"]
  releaseName: v${version}
git:
  commit: false
  tag: false
  push: false
  requireUpstream: false
  changelog: git log --pretty=format:"* %s (%h)" ${latestTag}...$(git for-each-ref refs/tags --sort=-taggerdate --format='%(refname)' --count=2 | tail -1)
