source "https://rubygems.org"

gem "rails", "~> 8.1.0"
gem "propshaft"
gem "puma"
gem "bootsnap", require: false
gem "hotwire-rails"
gem "vite_rails"
gem "slim-rails"
gem "redis"
gem "capistrano", "~> 3.19", require: false
gem "capistrano-rails", require: false
gem "capistrano-rbenv", require: false
gem "capistrano3-puma", require: false
gem "pg"
gem "mechanize", require: false
gem "pg_search"
gem "oj"
gem "curb"
gem "nokogiri"
gem "passwordless"
gem "csv", require: false
gem "good_job"
gem "sparql", require: false

group :development, :test do
  gem "debug", require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
  gem "dotenv"
end

group :development do
  gem "web-console"
  gem "letter_opener"
end

group :test do
  # Keep at 5 for now, as long as `rails test` doesn't pick up any tests:
  # https://github.com/minitest/minitest/issues/1040#issuecomment-3668131216
  gem "minitest", "< 6"
  gem "capybara"
  gem "selenium-webdriver"
  gem "webmock"
end
