#!/bin/bash

set -e

# build svelte
npm run build

# copy everything to a dist folder
rm -rf dist
mkdir dist
cp -r public/. dist/

# create hashed asset files (css, js)
hash1=$(head -c 12 /dev/urandom | shasum| cut -d' ' -f1)
mv dist/bundle.css dist/bundle-${hash1}.css
mv dist/bundle.css.map dist/bundle-${hash1}.css.map
sed -i "s/bundle\.css/bundle-${hash1}.css/g" dist/index.html dist/bundle-${hash1}.css.map

hash2=$(head -c 12 /dev/urandom | shasum| cut -d' ' -f1)
mv dist/bundle.js dist/bundle-${hash2}.js
mv dist/bundle.js.map dist/bundle-${hash2}.js.map
sed -i "s/bundle\.js/bundle-${hash2}.js/g" dist/index.html dist/bundle-${hash2}.js.map

hash3=$(head -c 12 /dev/urandom | shasum| cut -d' ' -f1)
mv dist/global.css dist/global-${hash3}.css
sed -i "s/global\.css/global-${hash3}.css/g" dist/index.html

# create gzip versions
for file in dist/*.{css,js,html,json,svg}; do
  [ -e "$file" ] || continue
  gzip -c $file > ${file}.gz
done
