name: Crystal CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-14.04, ubuntu-18.04, macOS-10.14, windows-2019]

    container:
      image: crystallang/crystal

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: shards install
      - name: Format check
        run: crystal tool format --check
      - name: Ameba (static code analysis)
        run: bin/ameba
